[env]
TERM = "xterm-256color"

# Force integer scaling (prevents fractional DPI rounding issues)
WINIT_X11_SCALE_FACTOR = "1.0"
WINIT_HIDPI_FACTOR = "1.0"

[window]
dynamic_padding = true
decorations = "Buttonless"

[font]
normal.family = "Comic Code Ligatures"
size = 12

# Subtle positional tuning
offset.x = 0
offset.y = 0
glyph_offset.x = 0
glyph_offset.y = 0

[[keyboard.bindings]]
key = "="
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "DecreaseFontSize"
