# Performance
backend = "glx";
vsync = true;
use-damage = true;

# Shadows & Corners
shadow = false;
corner-radius = 0; # Set to >0 for subtle rounded corners

# Fading
fading = false;
shadow = false;
